### ISSUE TITLE
Дискусия относно шрифта на ръководството

### ISSUE THREAD

**Issue by metala** [metala/php-the-right-way-l10n-bg_BG#9]
Здравейте на всички,

Днес разглеждах ръководството за пореден път и реших да го обновя според новият му облик, досущ като английската версия. След като качих промените на сайта, забелязах, че всъщност шрифта който се ползва е серифен (т.е. буквите са със столчета).
Лично на мен не ми допадат серифните шрифтове. Естествено това е лично мнение, но все пак искам да предложа за дискусия да сменим шрифта за българската версия на наръчника.

Има няколко свободни шрифта, които ползва "българска кирилица" и намирам за интересни:
http://npoekmu.me/%D0%B1%D0%B5%D0%B7%D0%BF%D0%BB%D0%B0%D1%82%D0%B5%D0%BD-%D1%88%D1%80%D0%B8%D1%84%D1%82-simbal-regular/

Освен това в самият сайт npoekmu.me, ползват Balezdrov (различен от Balezdrov11), който изглежда също е свободен и може да се свали от личният сайт на Светлин Балездров.

Моля за коментари.
Благодаря.

**Comment by ivanovyordan** [comment]
Аз като цяло харесвам sans шрифтове, като Open Sans и Helvetica, но и този ми харесва доста, а това, че ползва "българска", вместо "руска" кирилица е огромно предимство.

**Comment by VasilSlavchev** [comment]
Здравей, Simbal (от проектите.ме). мисля че е идеален като шрифт за ръководството. Няма да е лошо също да направиш една валидация на хтмл-ла на сайта. :)

**Comment by metala** [comment]
Качих обновление, където шрифта на сайта е сменен със Симбал. Може да изкажете мнение и да предложите промени.
